x=int(input("Ingresa un Numero: "))
y=int(input("Ingresa otro Numero: "))
R=(x-y)
S=(x+y)
D=(x/y)
M=(x*y)
Mod=(x%y)
print("La Resta es:",R)
print("La Suma es:",S)
print("La Division es:",D)
print("La Multiplicacion es:",M)
print("El Modulo es:",Mod)